apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: e2e-tests-dotnet-basic-zzjuqqjh-gitops
  description: This is GitOps manifest for e2e-tests-dotnet-basic-zzjuqqjh   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=e2e-tests-dotnet-basic-zzjuqqjh
    backstage.io/kubernetes-id: e2e-tests-dotnet-basic-zzjuqqjh 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: e2e-tests-dotnet-basic-zzjuqqjh-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:e2e-tests-dotnet-basic-zzjuqqjh
